- name: Deploy to EC2
  hosts: localhost
  connection: local

  tasks:
    - name: Launch EC2 instance
      amazon.aws.ec2:
        instance_type: t2.medium
        image: ami-04902260ca3d33422
        region: us-east-1
        key_name: devops
        vpc_subnet_id: subnet-0925e414c9f72ad43
        assign_public_ip: yes
        count: 1
        wait: true
        aws_access_key: "{{access_key}}"
        aws_secret_key: "{{secret_key}}"
        security_token: "{{session_token}}"
        # aws_access_key: "ASIA3OTZS6GX3GENTRNX"
        # aws_secret_key: "McC+kLv6i67ZNv+5GbCqUcUinFj3qk1GHhzcRIa7"
        # security_token: "FwoGZXIvYXdzEEwaDDpqY93KMJ4s9kxoWSK3AaZjMshw1ip/dH46WgcnqcU7g9f55u2DZ4veV9bxv0a4Gym+mTFKwBKWcPigiF0FCY99JfCk8PpVcRA4/4UYw9V0Aw/xzeHN+MQNoimRrva5m434VvTvjh8qABuHWgd9XoyDA14llaI85Nx6Uip3ri00NDSL3zw8CfC14HNrd+Y2riKJBIlm6axetnaHBl919+NZZs08syc56tpT1GrBFw8s7sqXaZHFPBn/I4kfByWFuYvkuJyQeijgp52NBjItUUh1jLzE3utkLs/g+f0wBEuLsswNK1MMeGCrnwRZTaQ/c68KhjTkaw9sP1oY"
      register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
      loop: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      delegate_to: "{{ item.public_dns_name }}"
      wait_for_connection:
        delay: 30
        timeout: 300
      loop: "{{ ec2.instances }}"

- name: Configure EC2
  hosts: launched
  connection: ssh

  tasks:
    - name: Add Centos extras
      shell: yum-config-manager --enable extras
      become: yes
    - name: Enable docker package
      shell: amazon-linux-extras enable docker
      become: yes
    - name: Install docker and GIT
      yum:
        name:
          - docker
          - git
        state: latest
        update_cache: yes
      become: yes
    - service:
        name: docker
        state: started
        enabled: yes
      become: yes
    - name: Set rights to docker
      shell: usermod -a -G docker ec2-user
      become: yes
    - name: Checkout git repo
      git:
        repo: "https://github.com/janlaskaj/4IT572_docker.git"
        dest: ./app
    - name: Build docker
      shell: cd app && docker build -t eshop:latest .
      become: yes
    - name: Run eshop
      shell: docker run -p 80:3000 eshop
      async: 45
      poll: 0
      become: yes
    - wait_for:
        port: 80
