- name: Deploy to EC2
  hosts: localhost
  connection: local

  tasks:
    - name: Launch EC2 instance
      amazon.aws.ec2:
        instance_type: t2.micro
        image: ami-04902260ca3d33422
        region: us-east-1
        key_name: devops
        vpc_subnet_id: subnet-09c7c11019dc5fa44
        assign_public_ip: yes
        count: 1
        group: eshop
        wait: true
        aws_access_key: "{{access_key}}"
        aws_secret_key: "{{secret_key}}"
        security_token: "{{session_token}}"
      register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
      loop: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      delegate_to: "{{ item.public_dns_name }}"
      wait_for_connection:
        delay: 30
        timeout: 300
      loop: "{{ ec2.instances }}"

- name: Configure EC2
  hosts: Launched
  connection: ssh

  tasks:
    - name: Add Centos extras
      shell: yum-congig-manager --enable extras
      become: yes
    - name: Enable docker package
      shell: amazon-linux-extras enable docker
      become: yes
    - name: Install docker and GIT
      yum:
        name:
          - docker
          - git
        state: latest
        update_cache: yes
      become: yes
    - service:
        name: docker
        state: started
        enabled: yes
    - name: Set rights to docker
      shell: usermod -a -G docker ec2-user
      become: yes
